### ISSUE TITLE
License in setup.py doesn't match the LICENSE file

### ISSUE THREAD

**Issue by jakub-olczyk** [martinrusev/python-daemon#4]
The `LICENSE` file contains MIT license and the `setup.py` file contains information about "BSD" license (which in itself is somewhat confusing because there are [at least 3 types of BSD licenses](https://en.wikipedia.org/wiki/BSD_license#Terms)).

Which licensing terms should I follow?

**Comment by martinrusev** [comment]
It is a MIT license

**Comment by jakub-olczyk** [comment]
Thanks for clarification!

Cheers!

**Comment by arpit1997** [comment]
Well this mistake is already corrected by @martinrusev on commit 8f3cdcbe7abfc299b973ebec3e3fcd9634b244
So should we close this issue now @martinrusev 
:small_red_triangle_down: :small_airplane: :smile:
